print("The love calculator is calculating your score......")
name1=input("Enter your name:")
name2=input("Enter their name:")
combined_name=(name1+name2).lower()
t=combined_name.count("t")
r=combined_name.count("r")
u=combined_name.count("u")
e=combined_name.count("e")
first_digit=str(t+r+u+e)
l=combined_name.count("l")
o=combined_name.count("o")
v=combined_name.count("v")
e=combined_name.count("e")
second_digit=str(l+o+v+e)
score=int(first_digit+second_digit)
# print(f"your love score is {score}")
if score<10 or score>90:
    print(f"your score is {score}, you go together like coke and mentos.")
elif score>40 and score<50:
    print(f"your score is {score}, youare alrighty together")
else:
    print(f"your score is {score}")