print("Welcome to the tip calculator.")
bill=float(input("What was the total bill?$"))
tip=int(input("What percentage tip would like to give? 10,12 or 15?"))
person=int(input("How many people to split the bill?"))
total_bill=bill+(bill*tip/100)
per_person_bill=round(total_bill/person,2)
print(f"Each person should pay:${per_person_bill}")